# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 54.144.130.5
  become: yes

  tasks:

- name: Call Roles
  hosts: 54.144.130.5
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   #- motd
   - copy
