# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 15.206.165.213
  become: yes

  tasks:

- name: Call Roles
  hosts: 15.206.165.213
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
   #- copy
