# ---
# # tasks file for /etc/ansible/roles/copy

# - name: Copy file
#   copy:
#     src: /home/2.txt
#     dest: /home/ubuntu/
#   become: yes
#   become_user: root

  - name: Clone the Git repository
    git:
      repo: "https://github.com/dheerajramesh/spring_project_school_of_dev.git"
      dest: "/home/sivakondla/dheeraj"
      clone: yes
      version: main

  - name: Build the Docker image
    shell: "cd /home/sivakondla/dheeraj  && docker build -t petclinic:v2  ."
    
  - name: Run the Docker image
    shell: "docker run -p 15000:8080 petclinic:v2"   
  
  - name: Wait for the Docker container to start
    wait_for:
    host: localhost
    port: 15000
    state: started
    timeout: 300  
