# ---
# # tasks file for /etc/ansible/roles/copy

# - name: Copy file
#   copy:
#     src: /home/2.txt
#     dest: /home/ubuntu/
#   become: yes
#   become_user: root

#   - name: Clone the Git repository
#     git:
#       repo: "https://github.com/dheerajramesh/spring_project_school_of_dev.git"
#       dest: "/home/dheeraj/siva"
#       clone: yes
#       version: main

#   - name: Build the Docker image
#     shell: "cd /home/dheeraj/siva  && docker build -t petclinic:v3  ."
    
#   - name: Run the Docker image
#     shell: "docker run --detach -p 10000:8080 petclinic:v3"   

  
 # - name: Wait for the Docker container to start
 #   wait_for:
 #     host: localhost
 #     port: 16000
 #     state: started
 #     timeout: 300  


---
- name: Install psutil using pip
  hosts: all
  become: yes
  
  tasks:
    - name: Install pip
      raw: test -e /usr/bin/pip || (curl https://bootstrap.pypa.io/get-pip.py | python)
      changed_when: False
      
    - name: Install psutil
      pip:
        name: psutil
        state: present
    - name: Run the script
      command: python https://github.com/dheerajramesh/AnsibleRoles/edit/main/roles/copy/tasks/utils.py


